[package]
name = "wind"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serenity = "0.12.5"
tokio = { version = "1.49.0", features = ["full"] }
log = "0.4"
env_logger = "0.11.8" 
serde = "1.0.228"
serde_json = "1.0.149"
chrono = "0.4.43"
dotenv = "0.15.0"
